[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "A",
    "ASYNC",
    "B",
    "C4",
    "C90",
    "E",
    "ERA",
    "F",
    "FBT",
    "FLY",
    "FURB",
    "I",
    "LOG",
    "N",
    "RET",
    "RUF",
    "PIE",
    "S",
    "SIM",
    "T20",
    "UP",
    "W",
]

fixable = ["ALL"]
unfixable = []

ignore=[
    "RUF012",  # Mutable class attributes should be annotated with `typing.ClassVar`
    "FBT001",  # Boolean-typed positional argument in function definition
    "FBT002",  # Boolean default positional argument in function definition
    "FBT003",  # Boolean positional value in function call
    "ERA001",  # Found commented-out code
    "LOG015",  # Use own logger instead
]


